Name:           dsp
Version:        2.0.1
Release:        1%{?dist}
Summary:        DNS Statistics Presenter
Group:          Productivity/Networking/DNS/Utilities

License:        BSD-3-Clause
URL:            https://www.dns-oarc.net/oarc/data/dsc
# Source needs to be generated by dist-tools/create-source-packages, see
# https://github.com/jelu/dist-tools
Source0:        %{name}_%{version}.orig.tar.gz

BuildArch:      noarch

BuildRequires:  perl
BuildRequires:  perl(Proc::PID::File)
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(DSC)
BuildRequires:  perl(CGI)
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool

Requires:       perl(Proc::PID::File)
Requires:       perl(XML::Simple)
Requires:       perl(DSC)
Requires:       perl(CGI)

%description
DNS Statistics Presenter (DSP) is a tool used for exploring statistics from
busy DNS servers collected by DNS Statistics Collector (DSC).

%prep
%setup -q -n %{name}_%{version}


%build
sh autogen.sh
%if 0%{?suse_version} > 0
%configure --with-cgi-bin-dir=/usr/lib/cgi-bin
%else
%configure
%endif
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root)
%config %{_sysconfdir}/*
%if 0%{?suse_version} > 0
/usr/lib/cgi-bin
%else
%{_libdir}/cgi-bin
%endif
%{_libexecdir}/dsp
%{_datadir}/doc/*
%{_datadir}/dsp


%changelog
* Mon Aug 05 2019 Jerry Lundström <lundstrom.jerry@gmail.com> 2.0.1-1
- Release 2.0.1
  * Minor fixes to Automake/Autoconf files, such as:
    - Fix #17: add DESTDIR
    - `autoreconf` include fix
    - `configure` Perl program check
    - Update m4 scripts to latest version
  * Commits:
    cb5b223 Package
    b7ef042 Funding
    44f0f9f Prepare SPEC for OSB/COPR
    e5d8987 RPM spec and various automake fixes
    d42557b Fix #17: add DESTDIR
    3358d7f Add Travis-CI build status
    f839d0f Fix travis script, only expand dir and test.
    52b5ca3 Add debian/ubuntu package files
* Thu Dec 15 2016 Jerry Lundström <lundstrom.jerry@gmail.com> 2.0.0-1
- Initial package
